Repository Inteli-College/2025-1B-T12-EC06-G03, pull requests merged in 2025-05, with the labels that each got.

#22 feat: adiciona estrutura de pastas inicial para o front
  src/frontend/.gitignore
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/postcss.config.js
  src/frontend/public/favicon.ico
  src/frontend/public/index.html
  src/frontend/public/logo192.png
  src/frontend/public/logo512.png
  src/frontend/public/manifest.json
  src/frontend/public/robots.txt
  src/frontend/src/Layout.jsx
  src/frontend/src/Router.jsx
  src/frontend/src/assets/logo.png
  src/frontend/src/components/SideBar.jsx
  src/frontend/src/index.css
  src/frontend/src/index.js
  src/frontend/src/pages/NotFound.jsx
  src/frontend/src/services/.gitkeep
  src/frontend/tailwind.config.js
Labels: feature

#23 Docs/falha-esp-32
  docs/docs/sprint_2/controle_drone/ESP32.md
  docs/docs/sprint_2/controle_drone/_category_.json
Labels: documentation

#27 docs: padroniza referencias
  docs/docs/sprint_1/entendimento-neg/matriz_de_riscos.md
  docs/docs/sprint_1/proposta-arq/arquitetura_da_solucao.md
  docs/docs/sprint_1/proposta-arq/requisitos_funcionais.md
  docs/docs/sprint_1/proposta-arq/requisitos_nao_funcionais.md
  docs/docs/sprint_1/ux/arquitetura_informacao/arquitetura_da_informacao.md
  docs/docs/sprint_1/ux/arquitetura_informacao/diagramas_de_sequencia.md
  docs/docs/sprint_1/ux/personas.md
  docs/docs/sprint_1/ux/user_stories.md
  docs/docs/sprint_1/ux/wireframes.md
Labels: documentation

#29 feat/Side Bar
  .github/workflows/ci.yml
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/Layout.jsx
  src/frontend/src/Router.jsx
  src/frontend/src/assets/logo-fundo-branco.svg
  src/frontend/src/components/SideBar.jsx
  src/frontend/src/styles/SideBar.css
Labels: feature, style

#25 docs: atualiza a arquitetura proposta
  docs/docs/sprint_2/controle_drone/arquitetura_atualizada.md
  docs/static/img/arquitetura_sprint2.png
Labels: documentation

#37 Docs/modelo
  docs/docs/sprint_2/modelo/_category_.json
  docs/docs/sprint_2/modelo/interface_modelo.md
  docs/docs/sprint_2/modelo/modelo.md
Labels: documentation

#40 Docs/streamlit
  docs/docs/sprint_2/modelo/interface_modelo.md
  docs/docs/sprint_2/modelo/modelo.md
  docs/static/img/imagem_classificada.png
  docs/static/img/upload_streamlit.jpeg
Labels: documentation

#45 style: altera estilizacao do hover nos botoes em visualizarProjetos
  src/frontend/src/components/ProjectSearch.jsx
  src/frontend/src/pages/VisualizarProjeto.jsx
Labels: style

#44 style: altera estilizacao do hover nos botoes
  src/frontend/src/Router.jsx
  src/frontend/src/components/ProjectCard.jsx
  src/frontend/src/components/ProjectElement.jsx
  src/frontend/src/components/ProjectImageCard.jsx
  src/frontend/src/components/ProjectRecent.jsx
  src/frontend/src/pages/ImageAnalysis.jsx
  src/frontend/src/pages/Projects.jsx
  src/package-lock.json
Labels: feature

#48 Docs/tela desc projeto
  docs/docs/sprint_2/plataforma_web/desc_projeto.md
  docs/static/img/descricao_alta_fidelidade.png
  docs/static/img/form_add_edif.png
  docs/static/img/logs.png
  docs/static/img/pagina_descricao.png
  docs/static/img/pagina_descricao_edicao.png
  src/frontend/src/pages/ImageAnalysis.jsx
Labels: documentation

#47 docs: inclui documentacao da tela projetos e analise de imagens
  docs/docs/sprint_2/plataforma_web/_category_.json
  docs/docs/sprint_2/plataforma_web/analise_imagens.md
  docs/docs/sprint_2/plataforma_web/projetos.md
Labels: documentation

#51 Docs/tela imagem drone e componente side bar
  docs/docs/sprint_2/plataforma_web/imagem-drone.md
  docs/docs/sprint_2/plataforma_web/side-bar.md
  docs/static/img/modal-confirmacao-projeto.png
  docs/static/img/modal-selecao-projeto.png
  docs/static/img/sidebar-expandida.png
  docs/static/img/sidebar-retraida.png
  docs/static/img/tela-imagem-drone1.png
  docs/static/img/tela-imagem-drone2.png
Labels: documentation

#54 feat: implement ProjetoController and ProjetoService for project mana…
  src/backend/src/main/java/com/athenas/athenas/controller/ProjetoController.java
  src/backend/src/main/java/com/athenas/athenas/dto/ProjetoDTO.java
  src/backend/src/main/java/com/athenas/athenas/model/Projeto.java
  src/backend/src/main/java/com/athenas/athenas/repository/ProjetoRepository.java
  src/backend/src/main/java/com/athenas/athenas/service/ProjetoService.java
  src/backend/src/main/java/com/athenas/athenas/service/UsuarioService.java
Labels: feature

#56 feat: add ci
  .github/workflows/ci-back.yml
  .github/workflows/ci-front.yml
  src/backend/src/main/java/com/athenas/athenas/controller/HealthCheckController.java
Labels: feature

#61 feat: cria CRUD pra tabela de empresa
  src/backend/src/main/java/com/athenas/athenas/controller/EmpresaController.java
  src/backend/src/main/java/com/athenas/athenas/dto/EmpresaDTO.java
  src/backend/src/main/java/com/athenas/athenas/repository/EmpresaRepository.java
  src/backend/src/main/java/com/athenas/athenas/service/EmpresaService.java
Labels: feature

#65 feat: adiciona autenticação no login e corrige referências problemáticas
  src/backend/pom.xml
  src/backend/src/main/java/com/athenas/athenas/DTO/EdificioDTO.java
  src/backend/src/main/java/com/athenas/athenas/DTO/UpdateViewProjetoRequest.java
  src/backend/src/main/java/com/athenas/athenas/DTO/ViewProjetoRequestDTO.java
  src/backend/src/main/java/com/athenas/athenas/DTO/ViewProjetoResponseDTO.java
  src/backend/src/main/java/com/athenas/athenas/controller/AuthController.java
  src/backend/src/main/java/com/athenas/athenas/controller/ViewProjetoController.java
  src/backend/src/main/java/com/athenas/athenas/service/AuthService.java
  src/backend/src/main/java/com/athenas/athenas/service/ViewProjetoService.java
  src/backend/src/main/java/com/athenas/athenas/utils/JwtUtil.java
  src/backend/src/main/resources/application.properties
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/Router.jsx
  src/frontend/src/components/LoadingModal.jsx
  src/frontend/src/components/PrivateRoutes.jsx
  src/frontend/src/components/SideBar.jsx
  src/frontend/src/components/SideBarProjetos.jsx
  src/frontend/src/httpClient.js
  src/frontend/src/pages/Login.jsx
Labels: bug, feature

#64 Docs/Backend-modelo
  docs/docs/sprint_3/backend_modelo/_category_.json
  docs/docs/sprint_3/backend_modelo/backend_modelo.md
Labels: documentation
